name: Deploy Preview to S3 + CloudFront

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
      PREVIEW_BUCKET: preview-pr-${{ github.event.pull_request.number }}-jp-aws-app
      BUILD_DIR: dist
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create S3 bucket
        run: |
          aws s3 mb s3://${{ env.PREVIEW_BUCKET }} --region $AWS_REGION
          aws s3 website s3://${{ env.PREVIEW_BUCKET }} --index-document index.html

      - name: Upload to S3
        run: aws s3 sync ${{ env.BUILD_DIR }}/ s3://${{ env.PREVIEW_BUCKET }} --delete

      - name: Create CloudFront distribution
        id: cloudfront
        run: |
          CF_DIST_ID=$(aws cloudfront create-distribution \
            --origin-domain-name "${{ env.PREVIEW_BUCKET }}.s3.amazonaws.com" \
            --default-root-object index.html \
            --query 'Distribution.Id' --output text)
          echo "distribution_id=${CF_DIST_ID}" >> $GITHUB_OUTPUT

      - name: Save CloudFront ID for cleanup
        run: |
          echo "CLOUDFRONT_ID=${{ steps.cloudfront.outputs.distribution_id }}" >> cloudfront.txt
          aws s3 cp cloudfront.txt s3://${{ env.PREVIEW_BUCKET }}/cloudfront.txt

      - name: Output Preview URL
        run: echo "Preview URL: https://${{ steps.cloudfront.outputs.distribution_id }}.cloudfront.net"
